language: python
python:
  - "3.8"
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt --use-feature=2020-resolver
script: 
  - python -m pytest -v tests/test_dice.py
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: dice-on-demand
  on:
    branch: main
    python: "3.8"
